services:
  web:
    container_name: web
    build: ./
    ports:
      - 80:80
    privileged: true
    volumes:
      - ./public-html/:/var/www/html/
      - ./node_modules/:/var/www/html/node_modules/