services:
  web:
    container_name: web
    build: ./
    ports:
      - 80:80
    privileged: true
    volumes:
      - ./public-html/:/var/www/html/
      - ./vendor/:/var/www/html/vendor/
  composer:
      image: composer
      command: "composer install"
      volumes:
        - ./:/app