version: '3'
services:
  app:
    restart: always
    build: .
    container_name: 'app'
    ports:
      - "8001:8001"
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:/root/src/
      - ~/.zshrc:/root/.zshrc
    networks: 
     - DOG_FOR_CAMPUS
    depends_on: 
    - mysql
  
    mysql:
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'DOG_FOR_CAMPUS'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
            - ./database/sql_migrations/:/docker-entrypoint-initdb.d
        networks:
            - DOG_FOR_CAMPUS
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]